name: Deploy On Tag

on:
  push:
    tags:        
      - '**'
    branches: 
      - 'release/**'
jobs:
  deploy-tag:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "deploy release branch on tag"